version: '3.3'

services:
  # EmbyTok 前端应用 - 简单版配置
  embytok:
    image: 1525745393/embytok:latest
    container_name: embytok-web
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production
    network_mode: bridge
