version: '3.3'

services:
  # EmbyTok 前端应用
  embytok:
    image: 1525745393/embytok:latest
    container_name: embytok-web
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production
    networks:
      - embytok-network

networks:
  embytok-network:
    driver: bridge
